apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: ravali218/test:1.0.17  # Replace with your Docker image URL
      ports:
        - containerPort: 80  # Example port your application listens on
