apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: ravali218/test:1.0.17 
      ports:
        - containerPort: 8080  
